export default {
  arrowParens: "avoid",
  bracketSameLine: false,
  bracketSpacing: true,
  plugins: [],
  printWidth: 120,
  proseWrap: "always",
  quoteProps: "as-needed",
  requirePragma: false,
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: "all",
  useTabs: true,
};
